version: '3.8'

services:
  # 管理后台
  frontend-admin:
    build:
      context: ./frontend-admin
      dockerfile: Dockerfile
    container_name: hospital-admin
    ports:
      - "8081:80"
    restart: unless-stopped

  # 用户端
  frontend-user:
    build:
      context: ./frontend-user
      dockerfile: Dockerfile
    container_name: hospital-user
    ports:
      - "8082:80"
    restart: unless-stopped
